[package]
name = "secret-chat"
version = "0.1.0"
authors = ["Markus Faerevaag <m@frv.ag>"]

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

[dependencies]
ws = "*"
openssl = "*"
rustc-serialize = "0.3"
